#!/usr/bin/env python3
import sys
import json
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate
from reportlab.lib.colors import HexColor, Color

# ── Colors ──────────────────────────────────────────────────────────────
DARK_BG     = HexColor('#08080e')
SURFACE     = HexColor('#191926')
ACCENT_BLUE = HexColor('#1a3fd4')
ACCENT2     = HexColor('#4d6fff')
RED         = HexColor('#d42020')
RED2        = HexColor('#ff4d4d')
TEAL        = HexColor('#2dd4bf')
AMBER       = HexColor('#fbbf24')
CORAL       = HexColor('#fb7185')
GREEN       = HexColor('#4ade80')
PURPLE      = HexColor('#c084fc')
TEXT        = HexColor('#f2f2f8')
TEXT2       = HexColor('#8888aa')
TEXT3       = HexColor('#505070')
BORDER      = HexColor('#2a2a3a')
WHITE       = colors.white

W, H = A4

def load_data(json_path):
    with open(json_path, 'r') as f:
        return json.load(f)

def draw_watermark(canvas_obj, doc, logo_path):
    canvas_obj.saveState()
    # Watermark logo — large, centered, semi-transparent
    if logo_path and os.path.exists(logo_path):
        canvas_obj.setFillColor(Color(1, 1, 1, alpha=0.04))
        canvas_obj.rect(0, 0, W, H, fill=1, stroke=0)
        img_w, img_h = 220, 90
        x = (W - img_w) / 2
        y = (H - img_h) / 2
        canvas_obj.setFillAlpha(0.06)
        try:
            canvas_obj.drawImage(logo_path, x, y, width=img_w, height=img_h,
                                  mask='auto', preserveAspectRatio=True)
        except Exception:
            pass
    canvas_obj.restoreState()

def draw_header(canvas_obj, doc, logo_path, project_name):
    canvas_obj.saveState()
    # Header bar
    canvas_obj.setFillColor(DARK_BG)
    canvas_obj.rect(0, H - 60, W, 60, fill=1, stroke=0)
    # Blue accent bar
    canvas_obj.setFillColor(ACCENT_BLUE)
    canvas_obj.rect(0, H - 63, W, 3, fill=1, stroke=0)
    # Logo in header
    if logo_path and os.path.exists(logo_path):
        try:
            canvas_obj.drawImage(logo_path, 20*mm, H - 50, width=70, height=28,
                                  mask='auto', preserveAspectRatio=True)
        except Exception:
            canvas_obj.setFont('Helvetica-Bold', 14)
            canvas_obj.setFillColor(WHITE)
            canvas_obj.drawString(20*mm, H - 40, 'PageOver')
    # Project name right side
    canvas_obj.setFont('Helvetica-Bold', 11)
    canvas_obj.setFillColor(TEXT2)
    canvas_obj.drawRightString(W - 20*mm, H - 28, project_name[:50])
    canvas_obj.setFont('Helvetica', 8)
    canvas_obj.setFillColor(TEXT3)
    canvas_obj.drawRightString(W - 20*mm, H - 40, 'PageOver Project Analysis Report')
    canvas_obj.restoreState()

def draw_footer(canvas_obj, doc, page_num, total_pages):
    canvas_obj.saveState()
    canvas_obj.setFillColor(SURFACE)
    canvas_obj.rect(0, 0, W, 28, fill=1, stroke=0)
    canvas_obj.setFillColor(ACCENT_BLUE)
    canvas_obj.rect(0, 28, W, 1, fill=1, stroke=0)
    canvas_obj.setFont('Helvetica', 8)
    canvas_obj.setFillColor(TEXT3)
    canvas_obj.drawString(20*mm, 10, 'Generated by PageOver — Intelligent Project Analysis Platform')
    canvas_obj.drawRightString(W - 20*mm, 10, f'Page {page_num}')
    canvas_obj.restoreState()

def severity_color(sev):
    if sev == 'high': return RED2
    if sev == 'medium': return AMBER
    return HexColor('#60a5fa')

def lang_hex(lang):
    LANG_COLORS = {
        'JavaScript':'#f7df1e','TypeScript':'#3178c6','Python':'#3572A5',
        'PHP':'#4F5D95','Java':'#b07219','C#':'#178600','C++':'#f34b7d',
        'C':'#555555','Ruby':'#701516','Go':'#00ADD8','Rust':'#dea584',
        'Swift':'#ffac45','Kotlin':'#A97BFF','Dart':'#00B4AB','HTML':'#e34c26',
        'CSS':'#563d7c','SCSS':'#c6538c','Shell':'#89e051','Vue':'#41b883',
    }
    return HexColor(LANG_COLORS.get(lang, '#8b8b8b'))

def generate_pdf(data, output_path, logo_path):
    story = []

    styles = getSampleStyleSheet()
    def S(name, **kw):
        return ParagraphStyle(name, **kw)

    title_style    = S('T', fontName='Helvetica-Bold', fontSize=22, textColor=TEXT, leading=28, spaceAfter=4)
    sub_style      = S('Sub', fontName='Helvetica', fontSize=10, textColor=TEXT2, leading=14, spaceAfter=2)
    h2_style       = S('H2', fontName='Helvetica-Bold', fontSize=13, textColor=TEXT, leading=18, spaceBefore=14, spaceAfter=6)
    h3_style       = S('H3', fontName='Helvetica-Bold', fontSize=10, textColor=ACCENT2, leading=14, spaceBefore=8, spaceAfter=4)
    body_style     = S('B', fontName='Helvetica', fontSize=9, textColor=TEXT2, leading=13)
    mono_style     = S('M', fontName='Courier', fontSize=8, textColor=TEAL, leading=12)
    tag_style      = S('Tag', fontName='Helvetica-Bold', fontSize=8, textColor=ACCENT2, leading=12)
    warn_style     = S('W', fontName='Helvetica', fontSize=9, textColor=TEXT, leading=13)
    red_b          = S('RB', fontName='Helvetica-Bold', fontSize=9, textColor=RED2, leading=12)
    center_style   = S('Ctr', fontName='Helvetica', fontSize=9, textColor=TEXT2, leading=13, alignment=TA_CENTER)

    project_name = data.get('project_name', 'Unnamed Project')
    source       = data.get('source_info', '')
    description  = data.get('description', '')
    languages    = data.get('languages', [])
    platforms    = data.get('platforms', [])
    bugs         = data.get('bugs', [])
    ai_usage     = data.get('ai_usage', {})
    availability = data.get('availability', [])
    files_sample = data.get('files_sample', [])
    uniqueness   = data.get('uniqueness', 0)
    overall      = data.get('overall_score', 0)
    file_count   = data.get('file_count', 0)
    total_size   = data.get('total_size', 0)
    stars        = data.get('stars', 0)
    forks        = data.get('forks', 0)

    def fmt_bytes(b):
        if b < 1024: return f'{b} B'
        if b < 1048576: return f'{b/1024:.1f} KB'
        return f'{b/1048576:.1f} MB'

    story.append(Spacer(1, 6*mm))

    # ── Title block ─────────────────────────────────────────────────────
    story.append(Paragraph(project_name, title_style))
    story.append(Paragraph(source[:80] if source else 'Uploaded file analysis', sub_style))
    if description:
        story.append(Paragraph(description[:200], sub_style))
    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=8))

    # ── Score Cards ──────────────────────────────────────────────────────
    story.append(Paragraph('Analysis Summary', h2_style))
    score_data = [
        ['OVERALL SCORE', 'UNIQUENESS', 'AI USAGE', 'TOTAL FILES', 'LANGUAGES'],
        [
            Paragraph(f'<b><font color="#4d6fff">{overall}/100</font></b>', S('sc',fontName='Helvetica-Bold',fontSize=18,textColor=ACCENT2,alignment=TA_CENTER,leading=22)),
            Paragraph(f'<b><font color="#2dd4bf">{uniqueness}%</font></b>', S('sc2',fontName='Helvetica-Bold',fontSize=18,textColor=TEAL,alignment=TA_CENTER,leading=22)),
            Paragraph(f'<b><font color="#c084fc">{ai_usage.get("score",0)}%</font></b>', S('sc3',fontName='Helvetica-Bold',fontSize=18,textColor=PURPLE,alignment=TA_CENTER,leading=22)),
            Paragraph(f'<b>{file_count:,}</b>', S('sc4',fontName='Helvetica-Bold',fontSize=18,textColor=AMBER,alignment=TA_CENTER,leading=22)),
            Paragraph(f'<b>{len(languages)}</b>', S('sc5',fontName='Helvetica-Bold',fontSize=18,textColor=CORAL,alignment=TA_CENTER,leading=22)),
        ]
    ]
    score_t = Table(score_data, colWidths=[None]*5, rowHeights=[18, 36])
    score_t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), SURFACE),
        ('BACKGROUND', (0,1), (-1,1), HexColor('#111118')),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,0), 7),
        ('TEXTCOLOR',  (0,0), (-1,0), TEXT3),
        ('ALIGN',      (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
        ('GRID',       (0,0), (-1,-1), 0.5, BORDER),
        ('ROWBACKGROUNDS', (0,1), (-1,1), [HexColor('#111118')]),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ('LINEABOVE',  (0,0), (-1,0), 1.5, ACCENT_BLUE),
    ]))
    story.append(score_t)
    story.append(Spacer(1, 6*mm))

    # ── AI Usage Label ───────────────────────────────────────────────────
    ai_label = ai_usage.get('label', '')
    if ai_label:
        label_color = RED2 if 'AI-Gen' in ai_label else (AMBER if 'Assisted' in ai_label else GREEN)
        story.append(Paragraph(f'AI Detection: <b><font color="{label_color.hexval() if hasattr(label_color,"hexval") else "#ff4d4d"}">{ai_label}</font></b>', S('AIL',fontName='Helvetica',fontSize=9,textColor=TEXT2,leading=13)))
        story.append(Spacer(1,3*mm))

    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=6))

    # ── Languages ────────────────────────────────────────────────────────
    if languages:
        story.append(Paragraph('Language Breakdown', h2_style))
        lang_rows = [['Language', 'Usage %', 'Size']]
        for l in languages[:12]:
            bar_w = max(2, int(l['percentage'] * 0.6))
            bar_cell = Table([['']],colWidths=[bar_w*mm],rowHeights=[6])
            bar_cell.setStyle(TableStyle([
                ('BACKGROUND',(0,0),(-1,-1), HexColor(l.get('color','#4d6fff'))),
                ('TOPPADDING',(0,0),(-1,-1),0),('BOTTOMPADDING',(0,0),(-1,-1),0),
                ('LEFTPADDING',(0,0),(-1,-1),0),('RIGHTPADDING',(0,0),(-1,-1),0),
            ]))
            lang_rows.append([
                Paragraph(f'<b>{l["name"]}</b>', S('LN',fontName='Helvetica-Bold',fontSize=9,textColor=TEXT,leading=12)),
                Paragraph(f'{l["percentage"]}%', S('LP',fontName='Courier',fontSize=9,textColor=TEXT2,leading=12)),
                Paragraph(fmt_bytes(l.get("bytes",0)), S('LS',fontName='Helvetica',fontSize=8,textColor=TEXT3,leading=12)),
            ])
        lang_t = Table(lang_rows, colWidths=[80*mm, 40*mm, 40*mm])
        lang_t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0), SURFACE),
            ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
            ('FONTSIZE',(0,0),(-1,0),8),
            ('TEXTCOLOR',(0,0),(-1,0),TEXT3),
            ('GRID',(0,0),(-1,-1),0.4,BORDER),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),[HexColor('#0f0f1a'),HexColor('#111118')]),
            ('TOPPADDING',(0,0),(-1,-1),5),
            ('BOTTOMPADDING',(0,0),(-1,-1),5),
            ('LEFTPADDING',(0,0),(-1,-1),8),
        ]))
        story.append(lang_t)
        story.append(Spacer(1, 5*mm))

    # ── Platforms ────────────────────────────────────────────────────────
    if platforms:
        story.append(Paragraph('Detected Platforms & Frameworks', h2_style))
        plat_names = ' | '.join([p['name'] for p in platforms])
        story.append(Paragraph(plat_names, S('PT',fontName='Helvetica-Bold',fontSize=10,textColor=TEAL,leading=16,spaceAfter=4)))
        story.append(Spacer(1,4*mm))

    # ── Bug Report ───────────────────────────────────────────────────────
    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=6))
    story.append(Paragraph('Bug & Issue Detection', h2_style))
    if bugs:
        high   = [b for b in bugs if b.get('severity')=='high']
        medium = [b for b in bugs if b.get('severity')=='medium']
        low    = [b for b in bugs if b.get('severity')=='low']
        story.append(Paragraph(f'Found <b>{len(bugs)}</b> issue(s): <font color="#ff4d4d">{len(high)} High</font>  <font color="#fbbf24">{len(medium)} Medium</font>  <font color="#60a5fa">{len(low)} Low</font>', body_style))
        story.append(Spacer(1,3*mm))
        bug_rows = [['Severity','Issue','File']]
        for b in bugs:
            sev = b.get('severity','low').upper()
            sc = severity_color(b.get('severity','low'))
            bug_rows.append([
                Paragraph(f'<b>{sev}</b>', S(f'BS{sev}',fontName='Helvetica-Bold',fontSize=7,textColor=sc,leading=10,alignment=TA_CENTER)),
                Paragraph(b.get('desc','')[:100], S('BD',fontName='Helvetica',fontSize=8,textColor=TEXT,leading=11)),
                Paragraph(b.get('file','')[:40], S('BF',fontName='Courier',fontSize=7,textColor=TEXT3,leading=10)),
            ])
        bug_t = Table(bug_rows, colWidths=[22*mm, 100*mm, 48*mm])
        bug_t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0), SURFACE),
            ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
            ('FONTSIZE',(0,0),(-1,0),8),
            ('TEXTCOLOR',(0,0),(-1,0),TEXT3),
            ('GRID',(0,0),(-1,-1),0.4,BORDER),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),[HexColor('#0f0f1a'),HexColor('#111118')]),
            ('TOPPADDING',(0,0),(-1,-1),5),
            ('BOTTOMPADDING',(0,0),(-1,-1),5),
            ('LEFTPADDING',(0,0),(-1,-1),6),
            ('ALIGN',(0,0),(0,-1),'CENTER'),
            ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
        ]))
        story.append(bug_t)
    else:
        story.append(Paragraph('No significant issues detected in the analyzed files.', S('NB',fontName='Helvetica',fontSize=9,textColor=GREEN,leading=13)))
    story.append(Spacer(1,5*mm))

    # ── AI Usage Signals ─────────────────────────────────────────────────
    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=6))
    story.append(Paragraph('AI Usage Analysis', h2_style))
    ai_score = ai_usage.get('score', 0)
    ai_signals = ai_usage.get('signals', {})
    story.append(Paragraph(f'AI Involvement Score: <b>{ai_score}%</b> — {ai_usage.get("label","Unknown")}', S('AIS',fontName='Helvetica-Bold',fontSize=10,textColor=PURPLE,leading=14,spaceAfter=6)))
    if ai_signals:
        sig_map = {
            'uniform_style':'Uniform Code Style','comment_density':'Comment Density',
            'naming_patterns':'AI Naming Patterns','boilerplate':'Boilerplate Code',
            'complexity_dist':'Complexity Distribution',
        }
        sig_rows = [['Signal','Score']]
        for key, label in sig_map.items():
            val = ai_signals.get(key, 0)
            sig_rows.append([
                Paragraph(label, body_style),
                Paragraph(f'{val}%', S('SV',fontName='Courier',fontSize=8,textColor=PURPLE,leading=12)),
            ])
        sig_t = Table(sig_rows, colWidths=[100*mm, 70*mm])
        sig_t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0),SURFACE),
            ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
            ('FONTSIZE',(0,0),(-1,0),8),
            ('TEXTCOLOR',(0,0),(-1,0),TEXT3),
            ('GRID',(0,0),(-1,-1),0.4,BORDER),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),[HexColor('#0f0f1a'),HexColor('#111118')]),
            ('TOPPADDING',(0,0),(-1,-1),5),
            ('BOTTOMPADDING',(0,0),(-1,-1),5),
            ('LEFTPADDING',(0,0),(-1,-1),8),
        ]))
        story.append(sig_t)
    story.append(Spacer(1,5*mm))

    # ── Availability ─────────────────────────────────────────────────────
    if availability:
        story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=6))
        story.append(Paragraph('Availability & Deployment', h2_style))
        for av in availability:
            status = av.get('status','unknown')
            sc = GREEN if status=='live' else CORAL
            story.append(Paragraph(
                f'<b><font color="{sc.hexval() if hasattr(sc,"hexval") else "#4ade80"}">{status.upper()}</font></b>  {av.get("label","")} — {av.get("url","")[:70]}',
                S('AV',fontName='Helvetica',fontSize=9,textColor=TEXT,leading=14)))
        story.append(Spacer(1,4*mm))

    # ── Files Sample ─────────────────────────────────────────────────────
    if files_sample:
        story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=6))
        story.append(Paragraph('File Structure (sample)', h2_style))
        for f in files_sample[:15]:
            fpath = f.get('path','')
            fsize = fmt_bytes(f.get('size',0))
            story.append(Paragraph(f'{fpath}  <font color="#505070">{fsize}</font>',
                S('FS',fontName='Courier',fontSize=8,textColor=TEXT2,leading=12)))

    # ─── Build PDF ────────────────────────────────────────────────────────
    page_num_holder = [0]

    def on_page(canvas_obj, doc):
        page_num_holder[0] += 1
        draw_watermark(canvas_obj, doc, logo_path)
        draw_header(canvas_obj, doc, logo_path, project_name)
        draw_footer(canvas_obj, doc, page_num_holder[0], 0)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=68, bottomMargin=36,
        title=f'PageOver Report — {project_name}',
        author='PageOver',
        subject='Project Analysis Report',
    )
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f'PDF generated: {output_path}')

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print('Usage: generate_pdf.py <data.json> <output.pdf> <logo.png>')
        sys.exit(1)
    data = load_data(sys.argv[1])
    generate_pdf(data, sys.argv[2], sys.argv[3])
